# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HappyBike' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HappyBike
  pod 'Alamofire', '~> 4.4'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'HappyBikeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HappyBikeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
